on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v4
        with:
          context: docker/debian-12.10-slim
          push: true
          tags: |
            ghcr.io/2chevskii/steamcmd:debian-12.10-slim
            ghcr.io/2chevskii/steamcmd:latest
    permissions:
      packages: write
