on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 5'
jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ./build-image.sh
        working-directory: docker/debian-12.10-slim
        env:
          GIT_REF_NAME: ${{ github.ref_name}}
          GIT_SHA: ${{ github.sha }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}
      - run: docker push --all-tags ghcr.io/2chevskii/steamcmd
      - run: docker push --all-tags docker.io/2chevskii/steamcmd
      - uses: peter-evans/dockerhub-description@v4
        with:
          repository: 2chevskii/steamcmd
          username: ${{ vars.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}
          short-description: ${{ github.event.repository.description }}
    permissions:
      packages: write
